# Generated by Django 5.2.7 on 2025-10-03 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FederationTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_id",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="任务编号"
                    ),
                ),
                (
                    "task_name",
                    models.CharField(max_length=100, verbose_name="任务名称"),
                ),
                ("description", models.TextField(blank=True, verbose_name="任务描述")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "运行中"),
                            ("paused", "已暂停"),
                            ("stopped", "已停止"),
                            ("completed", "已完成"),
                        ],
                        default="running",
                        max_length=20,
                        verbose_name="任务状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "current_epoch",
                    models.IntegerField(default=0, verbose_name="当前轮次"),
                ),
                (
                    "total_epochs",
                    models.IntegerField(default=100, verbose_name="总轮次"),
                ),
                (
                    "active_users",
                    models.IntegerField(default=0, verbose_name="活跃用户数"),
                ),
            ],
            options={
                "verbose_name": "联邦学习任务",
                "verbose_name_plural": "联邦学习任务",
            },
        ),
        migrations.CreateModel(
            name="TaskLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("info", "信息"),
                            ("warning", "警告"),
                            ("error", "错误"),
                            ("success", "成功"),
                        ],
                        default="info",
                        max_length=10,
                        verbose_name="日志级别",
                    ),
                ),
                ("message", models.TextField(verbose_name="日志内容")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="记录时间"),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="federation_app.federationtask",
                        verbose_name="任务",
                    ),
                ),
            ],
            options={
                "verbose_name": "任务日志",
                "verbose_name_plural": "任务日志",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TaskParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField(verbose_name="用户ID")),
                ("user_name", models.CharField(max_length=100, verbose_name="用户名")),
                (
                    "joined_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="加入时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否活跃"),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="federation_app.federationtask",
                        verbose_name="联邦任务",
                    ),
                ),
            ],
            options={
                "verbose_name": "任务参与者",
                "verbose_name_plural": "任务参与者",
                "unique_together": {("task", "user_id")},
            },
        ),
    ]
