# Generated by Django 5.2.7 on 2025-10-04 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("federation_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalAccuracy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("epoch", models.IntegerField(verbose_name="训练轮次")),
                ("accuracy", models.FloatField(verbose_name="全局准确度")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="记录时间"),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="global_accuracies",
                        to="federation_app.federationtask",
                        verbose_name="联邦任务",
                    ),
                ),
            ],
            options={
                "verbose_name": "全局准确度记录",
                "verbose_name_plural": "全局准确度记录",
                "ordering": ["epoch"],
                "unique_together": {("task", "epoch")},
            },
        ),
    ]
